import type { NextPage } from 'next';
import Head from 'next/head';
import { FormEvent, useState } from 'react';
import { useQueryClient } from 'react-query';
import { trpc } from '../utils/trpc';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>link.</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='container mx-auto flex flex-col items-center justify-center min-h-screen p-4'>
        <h1 className='text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700'>
          Tiny<span className='text-purple-300'>Link</span>.
        </h1>
        <InputForm />
      </main>
    </>
  );
};

const InputForm = () => {
  const [input, setInput] = useState('');
  const createUrl = trpc.useMutation('create');
  const last10ShortUrls = trpc.useQuery(['get']);
  const client = useQueryClient();

  const onClickHandler = (e: FormEvent) => {
    e.preventDefault();
    createUrl.mutate(
      {
        url: input,
      },
      {
        onSuccess() {
          setInput('');
          client.invalidateQueries('get');
        },
      },
    );
  };

  return (
    <div className='w-3/4'>
      <form onSubmit={onClickHandler}>
        <section className='flex flex-col text-centre justify-center p-6 duration-500 border-2 border-gray-500 rounded shadow-xl'>
          <div className='flex flex-row space-x-4'>
            <button className='text-lg text-purple-300 border p-2'>MAKE TINY</button>
            <input
              className='flex-1 text-center'
              onChange={(e) => setInput(e.target.value)}
              type='text'
              value={input}
            />
          </div>
        </section>
        <div className='text-white mt-5 p-5 grid auto-cols-min border-2 border-gray-500 rounded shadow-xl'>
          <h3 className='text-small leading-normal text-purple-300'>Previous 10 links:</h3>
          {last10ShortUrls?.data?.last10ShortUrls.map((row) => (
            <a className='text-small font-thin' key={row.id} href={window.location + row.slug}>
              {window.location + row.slug}
            </a>
          ))}
        </div>
      </form>
    </div>
  );
};

export default Home;
